WIP.

diff --git a/pairKey b/pairKey
--- a/pairKey
+++ b/pairKey
@@ -36,7 +36,7 @@ _ub_cksum_special_derivativeScripts_contents() {
 #export ub_setScriptChecksum_disable='true'
 ( [[ -e "$0".nck ]] || [[ "${BASH_SOURCE[0]}" != "${0}" ]] || [[ "$1" == '--profile' ]] || [[ "$1" == '--script' ]] || [[ "$1" == '--call' ]] || [[ "$1" == '--return' ]] || [[ "$1" == '--devenv' ]] || [[ "$1" == '--shell' ]] || [[ "$1" == '--bypass' ]] || [[ "$1" == '--parent' ]] || [[ "$1" == '--embed' ]] || [[ "$1" == '--compressed' ]] || [[ "$0" == "/bin/bash" ]] || [[ "$0" == "-bash" ]] || [[ "$0" == "/usr/bin/bash" ]] || [[ "$0" == "bash" ]] ) && export ub_setScriptChecksum_disable='true'
 export ub_setScriptChecksum_header='2591634041'
-export ub_setScriptChecksum_contents='255137647'
+export ub_setScriptChecksum_contents='3537925009'
 
 # CAUTION: Symlinks may cause problems. Disable this test for such cases if necessary.
 # WARNING: Performance may be crucial here.
@@ -13653,6 +13653,58 @@ _clean() {
 
 
 
+
+_openssl_seed-cygwin() {
+	python3 <<< '
+import string
+import os
+from os import urandom
+chars = string.ascii_letters + string.digits
+print("".join(chars[c % len(chars)] for c in urandom(16)))
+' | tr -dc 'a-zA-Z0-9'
+	python3 <<< 'import secrets
+import string
+alphabet = string.ascii_letters + string.digits
+print("".join(secrets.choice(alphabet) for i in range(16)))' | tr -dc 'a-zA-Z0-9'
+	python3 <<< '
+import string
+import os
+from os import urandom
+chars = string.ascii_letters + string.digits
+print("".join(chars[c % len(chars)] for c in urandom(16)))
+' | tr -dc 'a-zA-Z0-9'
+}
+
+_openssl_seed-linux() {
+	cat /dev/random | xxd -p | tr -d '\n' | head -c 32
+	cat /dev/urandom | xxd -p | tr -d '\n' | head -c 16
+}
+
+_openssl_seed-nix() {
+	cat /dev/random | xxd -p | tr -d '\n' | head -c 16
+	cat /dev/urandom | xxd -p | tr -d '\n' | head -c 32
+}
+
+
+
+_openssl_seed() {
+	# https://stackoverflow.com/questions/3854692/generate-password-in-python
+	# https://docs.python.org/3/library/os.html#os.urandom
+	if _if_cygwin
+	then
+		_openssl_seed-cygwin
+		return
+	elif uname -a 2>/dev/null | grep 'Linux' > /dev/null 2>&1
+	then
+		_openssl_seed-linux
+		return
+	else
+		_openssl_seed-nix
+		return
+	fi
+}
+
+
 _vectors_openssl_encrypt_procedure() {
 	echo 'test' > "$safeTmp"/testPlaintext
 	[[ $(head -c 48 "$safeTmp"/testPlaintext | xxd -p | tr -d '\n') != '746573740a' ]] && echo 'openssl: mismatch: testPlaintext' && _stop 1
@@ -13666,11 +13718,49 @@ _vectors_openssl_encrypt_procedure() {
 	[[ $(head -c 48 "$safeTmp"/testCiphertext | xxd -p | tr -d '\n') != 'bea2aadfed28b088843c58c95591430a' ]] && echo 'openssl: mismatch: testCiphertext' && _stop 1
 }
 
+_vectors_openssl_seed_procedure() {
+	if ! _openssl_seed > /dev/null 2>&1
+	then
+		echo 'fail: openssl: seed: exit status'
+	fi
+	if [[ $(_openssl_seed | wc -c ) != "48" ]]
+	then
+		echo 'openssl: seed: wc -c'
+	fi
+	if ! _openssl_seed-cygwin > /dev/null 2>&1
+	then
+		echo 'fail: openssl: seed-cygwin: exit status'
+	fi
+	if [[ $(_openssl_seed-cygwin | wc -c ) != "48" ]]
+	then
+		echo 'openssl: seed-cygwin: wc -c'
+	fi
+	if ! _openssl_seed-linux > /dev/null 2>&1
+	then
+		echo 'fail: openssl: seed-linux: exit status'
+	fi
+	if [[ $(_openssl_seed-linux | wc -c ) != "48" ]]
+	then
+		echo 'openssl: seed-linux: wc -c'
+	fi
+	if ! _openssl_seed-nix > /dev/null 2>&1
+	then
+		echo 'fail: openssl: seed-nix: exit status'
+	fi
+	if [[ $(_openssl_seed-nix | wc -c ) != "48" ]]
+	then
+		echo 'openssl: seed-nix: wc -c'
+	fi
+	return 0
+}
+
 
 _vectors_openssl_sequence() {
 	_start
 	
 	_vectors_openssl_encrypt_procedure
+	
+	_vectors_openssl_seed_procedure
 	
 	_stop
 }
@@ -13730,16 +13820,17 @@ _openssl_fifo_rand_sequence() {
 	
 	if ! _if_cygwin
 	then
-		head -c 48 /dev/urandom | xxd -p | tr -d '\n' | openssl enc -e "$currentCipher" -pass stdin -nosalt -md sha1 -in /dev/zero 2>/dev/null
+		head -c 48 /dev/urandom | xxd -p | tr -d '\n' | openssl enc -e "$currentCipher" -pass stdin -nosalt -pbkdf2 -in /dev/zero 2>/dev/null
 	else
 		# https://stackoverflow.com/questions/3854692/generate-password-in-python
+		# https://docs.python.org/3/library/os.html#os.urandom
 		python3 <<< '
 import string
 import os
 from os import urandom
 chars = string.ascii_letters + string.digits
 print("".join(chars[c % len(chars)] for c in urandom(48)))
-' | tr -dc 'a-zA-Z0-9' | xxd -p | tr -d '\n' | openssl enc -e "$currentCipher" -pass stdin -nosalt -md sha1 -in /dev/zero 2>/dev/null
+' | tr -dc 'a-zA-Z0-9' | xxd -p | tr -d '\n' | openssl enc -e "$currentCipher" -pass stdin -nosalt -pbkdf2 -in /dev/zero 2>/dev/null
 	fi
 	
 	#sleep 0.1
@@ -13970,6 +14061,12 @@ _php_password_to_key() {
 
 
 # NOTICE: Legacy. Configures and uses YubiKey OAUTH to generate matching time dependent passwords .
+# DANGER: Safe (including some, but only some, post-quantum safety). Short-term integrity (ie.  SHA3-256 length extension resistance vs. HMAC) was prioritized, confidentiality is only short-term (ie. AES-128-CFB).
+#  DANGER: There are *very* good technical reasons for these tradeoffs. Do not tinker with such algorithms unless you really know what you are doing.
+#  Good use case is transfer of software packages, with credentials, for installation, to an offline computer. Malware installed to the offline computer would be devastating, whereas partial loss of confidentiality would only affect credentials that were completely compromised soon enough.
+#  Another good use case is transfer of malware analysis out of or across separate network computers for public release or more analysis. Malware persisting with unanalyzed code on the separate network computer could reinfect the definitions, whereas loss of confidentiality may probably not be timely or complete enough for that to significantly reduce disinfection effectiveness.
+# WARNING: Algorims here, even for the reference implementation, may change, as expected uses are ephemeral, invalidating old data.
+# ATTENTION: All that said, this is very, very safe. The algorithms used, and the way these are used, is believed very, very, safe. Any issues are very highly theoretical. You have far more to worry about from malware, etc.
 
 
 _pair-generate() {
@@ -14046,6 +14143,9 @@ _pair-grab-stdout() {
 	#fi
 	#sleep 0.1
 	
+	
+	
+	
 	_messagePlain_request 'request: Please confirm presence at YubiKey at the minute.' > /dev/tty
 	while [[ $(date +%S | sed 's/^0//') -gt 0 ]]
 	do
@@ -14119,6 +14219,8 @@ _pair-header_received-hex() {
 #  'The Keccak hash function, that was selected by NIST as the SHA-3 competition winner, doesn't need this nested approach and can be used to generate a MAC by simply prepending the key to the message, as it is not susceptible to length-extension attacks.'
 # https://en.wikipedia.org/wiki/Authenticated_encryption
 #  'Encrypt-and-MAC' ... Same key is used.
+# https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_feedback_(CFB)
+#  
 _pair-enc() {
 	_start
 	
@@ -14147,7 +14249,7 @@ _pair-enc() {
 	if [[ $(cat "$safeTmp"/HMAC-output | xxd -p | tr -d '\n') == $(echo "$currentMessageSimple" | base64 -d | base64 -d | head -c 128 | tr -dc 'a-zA-Z0-9' | xxd -p | tr -d '\n') ]]
 	then
 		# decrypting
-		
+		true
 		
 		
 		
@@ -14207,6 +14309,12 @@ _pair-enc() {
 	_stop
 }
 
+
+
+
+_vector_pairKey() {
+	true
+}
 
 _test_pairKey() {
 	if ! type ykman > /dev/null 2>&1
