Draft.

diff --git a/planKey b/planKey
--- a/planKey
+++ b/planKey
@@ -36,7 +36,7 @@ _ub_cksum_special_derivativeScripts_contents() {
 #export ub_setScriptChecksum_disable='true'
 ( [[ -e "$0".nck ]] || [[ "${BASH_SOURCE[0]}" != "${0}" ]] || [[ "$1" == '--profile' ]] || [[ "$1" == '--script' ]] || [[ "$1" == '--call' ]] || [[ "$1" == '--return' ]] || [[ "$1" == '--devenv' ]] || [[ "$1" == '--shell' ]] || [[ "$1" == '--bypass' ]] || [[ "$1" == '--parent' ]] || [[ "$1" == '--embed' ]] || [[ "$1" == '--compressed' ]] || [[ "$0" == "/bin/bash" ]] || [[ "$0" == "-bash" ]] || [[ "$0" == "/usr/bin/bash" ]] || [[ "$0" == "bash" ]] ) && export ub_setScriptChecksum_disable='true'
 export ub_setScriptChecksum_header='2591634041'
-export ub_setScriptChecksum_contents='4020017855'
+export ub_setScriptChecksum_contents='2316847618'
 
 # CAUTION: Symlinks may cause problems. Disable this test for such cases if necessary.
 # WARNING: Performance may be crucial here.
@@ -18926,12 +18926,53 @@ _volatile_unmount() {
 	_volatile_umount "$@"
 }
 
+
+# Similar function used by 'flipKey' .
+_sweep_branch() {
+	_if_cygwin && ! _discoverResource-cygwinNative-ProgramFiles 'sdelete' 'sdelete' false
+	
+	if ! [[ -e "$1" ]]
+	then
+		return 1
+	fi
+	
+	if [[ -d "$1" ]]
+	then
+		return 1
+	fi
+	
+	if man wipe 2> /dev/null | grep 'Berke Durak' > /dev/null && man wipe 2> /dev/null | grep '\-Q <number\-of\-passes>' > /dev/null && man wipe 2> /dev/null | grep '\-s (silent mode)' > /dev/null
+	then
+		wipe -q -f -s "$@" > /dev/null
+		return 0
+	fi
+	
+	if _if_cygwin && type 'sdelete' > /dev/null 2>&1
+	then
+		local currentCygwinMSWpath
+		currentCygwinMSWpath=$(cygpath --windows "$1")
+		shift
+		sdelete -p 2 -r -nobanner "$currentCygwinMSWpath"
+		return 0
+	fi
+	
+	
+	return 1
+	
+}
+
 _sweep() {
+	[[ "$1" == "" ]] && return 1
+	[[ -d "$1" ]] && return 1
+	
+	_sweep_branch "$@"
+	
 	[[ -e "$1" ]] && rm -f "$@"
 	
 	! [[ -e "$1" ]] && return 0
 	return 1
 }
+
 
 # RESERVED. No production use.
 _clean() {
@@ -19254,6 +19295,50 @@ _php_password_to_key() {
 	stty echo > /dev/null 2>&1
 }
 
+
+
+# NOTICE: Legacy . Emphasizes integrity by using only GPG . Beware any CVEs against GPG . 
+
+
+# export fake home directory
+
+# fakehome gpg ...
+
+
+
+# openpgp -> yubikey
+
+# public key/recipient list ...
+
+
+
+
+
+
+
+
+
+
+
+
+
+ 
+_test_planKey() {
+	if ! type ykman > /dev/null 2>&1
+	then
+		echo 'missing: ykman'
+		return 1
+	fi
+	
+	if ! type gpg > /dev/null 2>&1
+	then
+		echo 'missing: gpg'
+		return 1
+	fi
+	
+	return 0
+}
+ 
 
 #currentReversePort=""
 #currentMatchingReversePorts=""
